#!/usr/bin/env bash
#I will make a loop of 10 and insert a condition
i=1
while [ $i -lt 10 ]
do
  if [ "$i" == '4' ]; then
    echo "bad luck"
	elif [ "$i" == '8' ]; then
    echo "good luck"
    else 
	echo "Best school"	
  fi
  ((i++))
done
