#!/usr/bin/env bash
#Create , diplay and signal
touch /var/run/myscript.pid
while :	
do 
echo "To infinity and beyond"
trap "echo I hate the kill command" 15
trap "echo Y U no love me?!" 2
trap "rm /var/run/myscript.pid" 3 15
done
