#!/usr/bin/env bash
#Script with (start, restart, stop)

case "$1" in 
start)
   ./manage_my_process &
   echo $!> /var/run/my_process.pid
   echo "manage_my_process started"
   ;;
stop)
   echo "manage_my_process stopped"
   pkill manage_my_process 
   rm /var/run/my_process.pid
   ;;
restart)
   echo "manage_my_process restarted"
   pkill manage_my_process 
   rm /var/run/my_process.pid
   ./manage_my_process &
   echo $!>/var/run/my_process.pid
   ;;
*)
   echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 1 
